# Allow anonymous connections on MQTT and WebSocket listener
# For internal dev use only - not for production

listener 1883
protocol mqtt
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true
